name: Test and Upload Coverage to Codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Write Secrets xcconfig
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p configuration
          echo "API_KEY = ${{ secrets.API_KEY }}" > configuration/Secrets.xcconfig

      # Keep this workaround
      - name: List available simulators (workaround)
        run: xcrun simctl list devices

      - name: Clean and Test Xcode project with coverage
        run: |
          set -euo pipefail
          xcodebuild clean test \
            -project sgairquality.xcodeproj \
            -scheme sgairquality \
            -testPlan sgairquality \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=26.2' \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            | xcpretty

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          xcode: true
          xcode_archive_path: TestResults.xcresult
